language: php
php:
- 5.5
script: phpunit Test.php

before_deploy: zip package.zip Test.php
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: package.zip
  skip_cleanup: true
  on:
    tags: true
